### ISSUE TITLE
please  improvement the doc

### ISSUE THREAD

**Issue by ibmsoft** [yakworks/gorm-rest-api#12]
i following the doc from https://yakworks.github.io/gorm-rest-api/quick-start/
can not install 
![image](https://user-images.githubusercontent.com/26042/34476316-abb7fb3e-efca-11e7-86bb-ad98e621feb7.png)

**Comment by basejump** [comment]
hi, we are in an active transition on a few things here for Grails 3.3. 
We should have something more accurate and working better by end of week.

**Comment by ibmsoft** [comment]
any progess?
