### ISSUE TITLE
RestApiRepoController

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-rest-api#13]
- [x]  change URLMappings to map to new action names
- [x] add trait for error handling as per docs http://docs.grails.org/latest/guide/theWebLayer.html#controllerExceptionHandling

- [x] add in mango query trait
  
- [x] RestApiRepoController needs to be completly rewritten and used by default instead of SimpleRestApiDomainController

**Comment by alexeyzvegintcev** [comment]
@basejump  do we really need mango query trait in controller, if we have it in repo?

**Comment by basejump** [comment]
where do you propose to add the actions? having a dedicated trait for the query and list actions seems the most organized and logical to me.

**Comment by alexeyzvegintcev** [comment]
I thought that query/list is a core functionality for controller and should be there,  but recalling as example repo and its size, probably you are right,  dedicated trait is better decision

**Comment by alexeyzvegintcev** [comment]
@basejump  please take a look on PR , I would like to start working on the last feature (set list or fields) in separate issue/branch not to make a PR to big
